### ISSUE TITLE
Tagset mappings?

### ISSUE THREAD

**Issue by erip** [UniversalDependencies/UD_Korean-Kaist#1]
Is there some accepted mapping from the various UD tagsets in the UD Korean corpora? I'm interested in combining all the train sets to create a master training set; before trying to develop a mapping myself, I'm curious if one already exists.

**Comment by martinpopel** [comment]
The advantage of UD is that it is universal, i.e. [the tagset](https://universaldependencies.org/u/pos/index.html) is the same for all languages (in addition to the UPOS part-of-speech tags, also [the set of dependency relation labels](https://universaldependencies.org/u/dep/index.html) is the same). There are [mappings from several non-UD tagsets](https://universaldependencies.org/tagset-conversion/index.html).

**Comment by erip** [comment]
@martinpopel I think this is only true for certain columns. :-) If you look at the XPOS column, for example, KAIST and GSD use different tagsets.

**Comment by dan-zeman** [comment]
Strictly speaking, XPOS is not a UD tagset. It is a place for storing a non-UD tag if desirable, so there could be anything and it is treebank-specific at best.
